package de.afa_amateurfunk.meshcore_packets.crypto;

import de.afa_amateurfunk.meshcore_packets.Util;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.security.InvalidParameterException;
import java.security.SecureRandom;
import java.util.Arrays;
import java.util.Random;

/**
 * Ed25519 private key in Meshcore format
 * <p>MeshCore uses orlp-ed25519, which uses NaCl's private key format of a || RH. This saves one round of SHA512 at load.</p>
 *
 * @see <a href="https://blog.mozilla.org/warner/2011/11/29/ed25519-keys/">Brian Warner on ed25519 keys</a>
 */
public class PrivateKey {
    /**
     * logger
     */
    private static final Logger LOG = LoggerFactory.getLogger(PrivateKey.class);
    /**
     * randomness generator, exposed to allow overriding it in unittests
     */
    protected static Random random = new SecureRandom();
    /**
     * the private key (64 bytes, a || RH)
     */
    protected byte[] privateKey;
    /**
     * seed (may be null if this represents a private key only loaeed from a || RH - cannot be calculated back!)
     */
    protected byte[] seed;
    /**
     * derived public key
     */
    protected PublicKey publicKey;

    /**
     * Construct a random private key
     */
    public PrivateKey() {
        byte[] seed = new byte[32];
        random.nextBytes(seed);
        LOG.trace("Attempting to create private key by random seed {}", Util.hexFormat.formatHex(seed));
        loadSeed(seed);
        this.publicKey = new PublicKey(Ed25519.derive_pubkey_orlp(this.privateKey));
        LOG.trace("Created new private key {}", Util.hexFormat.formatHex(this.privateKey));
    }

    /**
     * construct a PrivateKey instance from an a||RH private key (MeshCore) or seed
     *
     * @param privateKey raw key material
     */
    public PrivateKey(byte[] privateKey) {
        LOG.trace(String.format("Attempting to construct private key from buffer %s", Util.hexFormat.formatHex(privateKey)));
        if (privateKey.length == 64)
            loadOrlp(privateKey);
        else if (privateKey.length == 32)
            loadSeed(privateKey);
        else
            throw new InvalidParameterException("privateKey must be exactly 32 (seed) or 64 (orlp) bytes long");

        this.publicKey = new PublicKey(Ed25519.derive_pubkey_orlp(this.privateKey));
        LOG.trace("Created private key {}", Util.hexFormat.formatHex(this.privateKey));
    }

    /**
     * construct a PrivateKey instance from an a||RH private key (MeshCore) or seed and a saved public key, ensuring that the public key corresponds to the private key
     *
     * @param privateKey raw key material
     */
    public PrivateKey(byte[] privateKey, byte[] publicKey) {
        this(privateKey);
        // At this point, this.publicKey will contain the public key derived from the private key, check if it matches
        if (!Arrays.equals(this.publicKey.getPublicKey(), publicKey))
            throw new InvalidParameterException("Given publicKey does not match derived publicKey");
    }


    /**
     * initialize with a 32-byte long seed
     *
     * @param seed 32 random bytes
     */
    private void loadSeed(byte[] seed) {
        if (seed.length != 32)
            throw new InvalidParameterException("seed for privateKey must be exactly 32 bytes long");
        this.seed = seed;
        this.privateKey = Ed25519.seed_to_orlp(this.seed);
        this.validateKey();
    }

    private void loadOrlp(byte[] privateKey) {
        if (privateKey.length != 64)
            throw new InvalidParameterException("orlp-style privateKey must be exactly 64 bytes long");
        this.seed = null; //cannot recover seed, as orlp = sha512(seed)
        this.privateKey = privateKey;
        this.validateKey();
    }

    /**
     * Validate an a||RH key against MeshCore constraints
     *
     * @see <a href="https://github.com/agessaman/meshcore-web-keygen/blob/main/index.html#L934">agessaman implementation</a>
     * @see <a href="https://github.com/meshcore-dev/MeshCore/blob/main/src/Identity.cpp#L51">upstream implementation</a>
     */
    private void validateKey() {
        // Length of a||RH can already be assumed to be valid - if generated from random or seed, it will be generated by us, if loaded straight in, there's a validation there
        // Validation 1: private key (clamped scalar, a) must not be all-zero (indicates corrupt save/restore)
        byte[] a = new byte[32];
        System.arraycopy(this.privateKey, 0, a, 0, 32);
        boolean nonzeroFound = false;
        for (byte b : a) {
            if (b != 0x00) {
                nonzeroFound = true;
                break;
            }
        }
        if (!nonzeroFound) {
            throw new InvalidParameterException("privateKey scalar is all zeroes");
        }
        // Validation 2: RH of expanded key must not be all-zero
        byte[] rh = new byte[32];
        System.arraycopy(this.privateKey, 32, rh, 0, 32);
        nonzeroFound = false;
        for (byte b : rh) {
            if (b != 0x00) {
                nonzeroFound = true;
                break;
            }
        }
        if (!nonzeroFound) {
            throw new InvalidParameterException("privateKey RH is all zeroes");
        }
        // Validation 3: Check clamping of a. Should not happen in derivation from seed as it's done there, but may happen when user enters random a||RH key
        // More details: https://jcraige.com/an-explainer-on-ed25519-clamping
        // Also, read up pruneScalar in org.bouncycastle.math.ec.rfc8032.Ed25519
        // byte 0: r[0] &= 0xF8;
        if ((a[0] & 7) != 0) {
            throw new InvalidParameterException("privateKey first byte isn't properly clamped (bits 0-2 should be 0)");
        }
        // byte 31: r[SCALAR_BYTES - 1] &= 0x7F; => force bit 7 to 0
        // byte 31: r[SCALAR_BYTES - 1] |= 0x40; => force bit 6 to 1
        // Result: the byte should be 0b01abcdef, which means checking with 0xC0/0b11000000 should yield 0x40/0b01000000 for a properly clamped byte
        if ((a[31] & 0xC0) != 0x40) {
            throw new InvalidParameterException("privateKey last byte isn't properly clamped (bit 6 should be 1, bit 7 should be 0)");
        }

        // Validations on the public key are done during publicKey instantiation or, in the case of the derivation check, in the constructor
        // MeshCore also validates if a shared secret can be established with a well-known test key pair. We skip that.
    }

    /**
     * get the associated public key
     *
     * @return public key instance
     */
    public PublicKey getPublicKey() {
        return publicKey;
    }

    /**
     * get private key
     *
     * @return private key
     */
    public byte[] getPrivateKey() {
        return privateKey;
    }

    /**
     * sign a message with this key
     *
     * @param message message to be signed
     * @return signature
     */
    public byte[] sign(byte[] message) {
        byte[] ret = new byte[64];
        LOG.trace("Attempting to sign message {}", Util.hexFormat.formatHex(message));
        Ed25519.sign_orlp(ret, message, this.privateKey);
        LOG.trace("Signed message, signature {}", Util.hexFormat.formatHex(ret));
        return ret;
    }

    @Override
    public String toString() {
        return "PrivateKey{" +
                "seed=" + (seed == null ? "null" : Util.hexFormat.formatHex(seed)) +
                ", privateKey=" + Util.hexFormat.formatHex(privateKey) +
                ", publicKey=" + publicKey +
                '}';
    }

    public byte[] getSeed() {
        return seed;
    }
}
